### ISSUE TITLE
Inner single quotes are not escaped

### ISSUE THREAD

**Issue by LucasPickering** [LucasPickering/env-select#65]
With this config:

```toml
[applications.server.profiles.dev]
variables.BROKEN = "'; echo bobby tables '"
```

You get this:

```
> es set server dev
The following variables will be set:
BROKEN = '; echo bobby tables '
bobby tables
```

Oops! Nothing should be printed there. Offending core is [here](https://github.com/LucasPickering/env-select/blob/master/src/shell.rs#L118).
